INFO:httpx:HTTP Request: POST https://zukijourney.xyzbot.net/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://zukijourney.xyzbot.net/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
INFO:openai._base_client:Retrying request to /chat/completions in 0.941573 seconds
INFO:httpx:HTTP Request: POST https://zukijourney.xyzbot.net/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
INFO:openai._base_client:Retrying request to /chat/completions in 1.618573 seconds
INFO:httpx:HTTP Request: POST https://zukijourney.xyzbot.net/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
INFO:together:error_code=invalid_api_key error_message='Invalid API key provided. You can find your API key at https://api.together.xyz/settings/api-keys.' error_param=None error_type=invalid_request_error message='Together API error received' stream_error=False
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_llm_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_chain_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_chain_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_chain_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
INFO:httpx:HTTP Request: POST https://zukijourney.xyzbot.net/v1/chat/completions "HTTP/1.1 524 "
INFO:openai._base_client:Retrying request to /chat/completions in 0.990302 seconds
INFO:httpx:HTTP Request: POST https://zukijourney.xyzbot.net/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://zukijourney.xyzbot.net/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
INFO:openai._base_client:Retrying request to /chat/completions in 0.777525 seconds
INFO:httpx:HTTP Request: POST https://zukijourney.xyzbot.net/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
INFO:openai._base_client:Retrying request to /chat/completions in 1.547659 seconds
INFO:httpx:HTTP Request: POST https://zukijourney.xyzbot.net/v1/chat/completions "HTTP/1.1 524 "
INFO:together:error_code=invalid_api_key error_message='Invalid API key provided. You can find your API key at https://api.together.xyz/settings/api-keys.' error_param=None error_type=invalid_request_error message='Together API error received' stream_error=False
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_llm_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_chain_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_chain_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_chain_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
INFO:together:error_code=invalid_api_key error_message='Invalid API key provided. You can find your API key at https://api.together.xyz/settings/api-keys.' error_param=None error_type=invalid_request_error message='Together API error received' stream_error=False
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_llm_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
INFO:httpx:HTTP Request: POST https://zukijourney.xyzbot.net/v1/chat/completions "HTTP/1.1 524 "
INFO:openai._base_client:Retrying request to /chat/completions in 0.918117 seconds
INFO:httpx:HTTP Request: POST https://zukijourney.xyzbot.net/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://zukijourney.xyzbot.net/v1/chat/completions "HTTP/1.1 524 "
INFO:openai._base_client:Retrying request to /chat/completions in 0.868908 seconds
INFO:httpx:HTTP Request: POST https://zukijourney.xyzbot.net/v1/chat/completions "HTTP/1.1 524 "
INFO:openai._base_client:Retrying request to /chat/completions in 1.619434 seconds
INFO:httpx:HTTP Request: POST https://zukijourney.xyzbot.net/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
INFO:together:error_code=invalid_api_key error_message='Invalid API key provided. You can find your API key at https://api.together.xyz/settings/api-keys.' error_param=None error_type=invalid_request_error message='Together API error received' stream_error=False
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_llm_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_chain_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_chain_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_chain_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
INFO:together:error_code=model_not_found error_message='Unable to access model "mistralai/Mixtral-8x22B-Instruct-v0.1". Please visit https://api.together.xyz to see the list of supported models or contact the owner to request access.' error_param=None error_type=invalid_request_error message='Together API error received' stream_error=False
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_llm_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_chain_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_chain_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_chain_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
INFO:together:error_code=model_not_found error_message='Unable to access model "mistralai/Mixtral-8x22B-Instruct-v0.1". Please visit https://api.together.xyz to see the list of supported models or contact the owner to request access.' error_param=None error_type=invalid_request_error message='Together API error received' stream_error=False
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_llm_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_chain_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_chain_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
WARNING:langchain_core.callbacks.manager:Error in LangChainTracer.on_chain_error callback: TypeError('Object of type CaseInsensitiveDict is not JSON serializable')
